### ISSUE TITLE
Dropout Theano Error caused by theano.config.compute_test_value flag

### ISSUE THREAD

**Issue by raddy** [aigamedev/scikit-neuralnetwork#46] opened 2015-05-12 09:54 UTC
I've been trying to use dropout with Regressor either as a global parameter to the MLP or as a layer parameter, but have been getting Theano errors. Perhaps more of a PyLearn2 issue..

ValueError: Cannot compute test value; in put 0 (A) of Op <theano.sandbox.rng_mrg.DotModulo object at 0x7fea41e44b10>(A, s, m, A2, s2, m2) missing default value

**Comment by alexjc** [comment] 2015-05-12 22:18
Thanks for reporting this. Do you have more information about your dataset size, what neural network structure you used, and if there were any other parameters?  Ideally you can paste your setup code here!

We have some basic coverage tests for dropout (single iteration) and they currently run OK with the latest PyLearn2.

**Comment by alexjc** [comment] 2015-05-14 12:13
@raddy `plot_mlp.py -p regularize` also works from the latest revision. Not sure what the problem is with your specific data, but it's not a general problem. If you don't have more information, I'll close this ticket, can't reproduce.

**Comment by raddy** [comment] 2015-05-14 13:35
Yeah, this can be closed. The issue is in compute_test_value flag for Theano which needs to be false, but I believe gets set to true through pymc installation. Removing .theano and rebuilding fixes it.

**Comment by alexjc** [comment] 2015-05-14 13:40
@raddy Is there a way to catch this within the Python code at runtime, e.g. checking `theano.config` maybe?

**Comment by raddy** [comment] 2015-05-14 14:24
I'm not entirely sure, but I had to clean out the theano cache before that change took effect.

**Comment by alexjc** [comment] 2015-05-14 15:09
@raddy is this only a problem with dropout, or any neural network? I can assert for `theano.config.compute_test_value` I think.

**Comment by alexjc** [comment] 2015-05-15 22:21
Changed the title so others can find this if a problem occurs, but I don't think it's worth catching this in the code currently.

**Closed by alexjc** 2015-05-15 22:21 UTC
