### ISSUE TITLE
Question:get_params function doesn't work.

### ISSUE THREAD

**Issue by laesunk** [aigamedev/scikit-neuralnetwork#143] opened 2015-12-03 10:11 UTC
1) I initialized Regressor. but i can't get weights of each layer with get_params function
    weights field is None. is there any fault by me? or can't i get weights?

**Comment by alexjc** [comment] 2015-12-03 11:21
The weights are only available once you've called `_initialize` (internal function) or `fit` (external API). Did you use `get_parameters`? `get_params` is standard from scikit-learn, just returns everything raw.

**Comment by laesunk** [comment] 2015-12-03 15:22
yes i fit with my data. but model doesn't return weights..

**Comment by alexjc** [comment] 2015-12-03 17:14
Sorry, I can't help unless you're more specific what the problem is and how to reproduce.

**Comment by laesunk** [comment] 2015-12-06 05:59
i initiate Regressor with below code.
nn = Regressor(
    layers=[
        Layer("Tanh", units=20),
        Layer("Linear")],
    learning_rate=0.02,
    n_iter=10
)

and fit with below data

x_ = np.array([[12,31,3],[1,4,1]])

y_ = np.array([[10],[1]])

Regressor return below result

Regressor(batch_size=1, debug=False, dropout_rate=None, f_stable=0.001,
     hidden0=<sknn.nn.Layer `Tanh`: units=20, name=u'hidden0', frozen=False>,
     layers=[<sknn.nn.Layer `Tanh`: units=20, name=u'hidden0', frozen=False>, <sknn.nn.Layer `Linear`: units=1, name=u'output', frozen=False>],
     learning_momentum=0.9, learning_rate=0.02, learning_rule=u'sgd',
     loss_type=None, mutator=None, n_iter=10, n_stable=10,
     output=<sknn.nn.Layer `Linear`: units=1, name=u'output', frozen=False>,
     random_state=None, regularize=None, valid_set=None, valid_size=0.0,
     verbose=None, warning=None, weight_decay=None, weights=None)

please let me know which part i missed.
 
thanks

**Comment by alexjc** [comment] 2015-12-06 08:11
Assuming you use the version from the master branch, you need to call `get_parameters` on the Regressor. Should just work!

**Comment by laesunk** [comment] 2015-12-06 10:01
i installed with instruction "pip install scikit-neuralnetwork" 
is it master branch??
and i called get_parameters  function. but i can't get any result

**Comment by alexjc** [comment] 2015-12-06 14:01
It's probably different code. See this: https://github.com/aigamedev/scikit-neuralnetwork/issues/132
You can look at instructions on the front page for installing from Git.

**Comment by laesunk** [comment] 2015-12-07 01:19
yes i already installed from git and use master branch 
can you show me normal weight value of get_params() after fitting

**Comment by alexjc** [comment] 2015-12-07 08:53
Did you try this? https://github.com/aigamedev/scikit-neuralnetwork/blob/master/docs/guide_intermediate.rst#extracting-parameters

**Comment by laesunk** [comment] 2015-12-08 02:21
Thanks alexjc. i got it 
i missed that function is not get_params(). it's get_parameters()
i think get_params() is scikit-learn method

**Comment by alexjc** [comment] 2015-12-08 23:08
OK, closing this issue.

**Closed by alexjc** 2015-12-08 23:08 UTC
